www/src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    # url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

www/src/deployments/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

urlpatterns = [

    # Deployments
    url(r'^$', 
        login_required(views.DeploymentListView.as_view()), name="list"),
    url(r'^create/$', 
        login_required(views.DeploymentCreateView.as_view()), name="create"),
    url(r'^github_import/$', 
        login_required(views.DeploymentGithubImportView.as_view()), name="github_import"),
    url(r'^detail/(?P<slug>[-\w]+)/$', 
        login_required(views.DeploymentDetailView.as_view()), name='detail'),

    # Ingestions
    url(r'^detail/(?P<deployment_designator>[-\w]+)/new-ingestion$', 
        login_required(views.IngestionCreateView.as_view()), name='ingestion_create'),
    url(r'^detail/(?P<deployment_designator>[-\w]+)/ingestions/(?P<index>[-\w]+)$', 
        login_required(views.IngestionDetailView.as_view()), name='ingestion_detail'),
    ]

www/src/diman/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import deployments.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^deployments/', include(deployments.urls, namespace='deployments')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

www/src/deployments/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Div

from deployments import models
from deployments.settings import INGESTOR_OPTIONS


class DeploymentCreateFromCSVForm(forms.Form):
    csv_file = forms.FileField(label="CSV File")

INGESTOR_HELP_TEXTS = {k: 'Leave blank to use default value: <em>%s</em>' % v for k, v in INGESTOR_OPTIONS.iteritems()}
INGESTOR_DESCRIPTIVE_HELP_TEXTS = {
    'test_mode': 'Test Mode will run through the ingestion process without pushing any files to the QPID queues.', 
    'force_mode': 'Force Mode will ignore EDEX log files for records of previous ingestions and ingest all matching files.',
    'no_edex': 'The Ingestor will automatically check to see if EDEX services are alive between each file ingestion. Selecting this option will turn this off.',
    }
for k in INGESTOR_HELP_TEXTS:
    if INGESTOR_DESCRIPTIVE_HELP_TEXTS.get(k, False):
        INGESTOR_HELP_TEXTS[k] = "%s<br><br>%s" % (INGESTOR_DESCRIPTIVE_HELP_TEXTS[k], INGESTOR_HELP_TEXTS[k])

class IngestionForm(forms.ModelForm):
    class Meta:
        model = models.Ingestion
        exclude = ('deployment', 'timestamp', 'status', 'index')
        help_texts = INGESTOR_HELP_TEXTS

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'id-ingestionForm'
        self.helper.form_method = 'post'
        self.helper.form_action = ''
        self.helper.layout = Layout(
            Div(
                Div(
                    Fieldset(
                        'Switches', 
                        'test_mode', 'force_mode', 'health_check_enabled', 
                        css_class="col-md-3", ),
                    Fieldset(
                        'File Ingestion', 
                        'sleep_timer', 'max_file_age', 'start_date', 'end_date', 'quick_look_quantity', 
                        css_class="col-md-3", ),
                    Fieldset(
                        'QPID', 
                        'qpid_host', 'qpid_port', 'qpid_user', 'qpid_password', 
                        css_class="col-md-3", ),
                    Fieldset(
                        'EDEX', 
                        'edex_command', 'cooldown', 'no_edex', 
                        css_class="col-md-3", ),
                    css_class="row", ),
                Div(
                    ButtonHolder(Submit('submit', 'Submit'), css_class="col-md-12"),
                    css_class="row", ),
                )
            )
        super(IngestionForm, self).__init__(*args, **kwargs)

www/src/deployments/views.py
from github import Github
from StringIO import StringIO

from django.contrib import messages
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic 

from deployments.models import Deployment, Ingestion
from deployments.forms import DeploymentCreateFromCSVForm, IngestionForm
from deployments import tasks
from deployments.settings import INGESTOR_OPTIONS, GITHUB_TOKEN

class DeploymentListView(generic.ListView):
    model = Deployment

    def get_queryset(self):
        filters = {
            'platform__reference_designator': self.request.GET.get('platform', None), 
            'number': self.request.GET.get('number', None), 
            'data_source__name': self.request.GET.get('data_source', None), 
            'data_source__abbr': self.request.GET.get('data_source_abbr', None), 
            }
        filters = {f: filters[f] for f in filters if filters[f]}
        return Deployment.objects.filter(**filters)

class DeploymentDetailView(generic.DetailView):
    model = Deployment

    def get_object(self):
        try:
            return Deployment.get_by_designator(self.kwargs.pop('slug', None))
        except:
            raise Http404(u"No deployment found.")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if "_process_csv" in request.POST:
            self.object.process_csv()
            self.object.log_action(request.user, 
                "Processed CSV and created %d new data groups." % self.object.data_groups.count())
        return HttpResponseRedirect(self.object.get_absolute_url())

class DeploymentCreateView(generic.edit.FormView):
    template_name = "deployments/deployment_form.html"
    form_class = DeploymentCreateFromCSVForm

    def form_valid(self, form):
        csv_file = form.cleaned_data.get('csv_file', None)
        try:
            self.new_deployment = Deployment.create_from_csv_file(csv_file)
            self.new_deployment.log_action(self.request.user, "Created.")
        except Deployment.AlreadyExists, e:
            msg = "%s %s." % (e.message, e.html_link_to_object("View the deployment"))
            messages.warning(self.request, msg)
            return super(DeploymentCreateView, self).form_invalid(form)
        except Deployment.BadDesignator, e:
            msg = "%s Check that the file name is correct." % (e, message)
            messages.warning(self.request, e.message)
            return super(DeploymentCreateView, self).form_invalid(form)
        else:
            self.new_deployment.process_csv()
            self.new_deployment.log_action(self.request.user, 
                "Processed CSV and created %d new data groups." % self.new_deployment.data_groups.count())
        return super(DeploymentCreateView, self).form_valid(form)

    def get_success_url(self):
        return self.new_deployment.get_absolute_url()

class DeploymentGithubImportView(generic.TemplateView):
    template_name = "deployments/deployment_github_import.html"

    def post(self, request, *args, **kwargs):
        if "_import" in request.POST:
            repository = [
                o for o 
                in Github(GITHUB_TOKEN).get_user().get_orgs() 
                if o.login=='ooi-integration'
                ][0].get_repo('ingestion-csvs')

            def get_csvs(repo, filepath, _csv_files={}):
                for item in repo.get_dir_contents(filepath):
                    if "#" in item.path:
                        continue
                    if item.type == "dir":
                        print item.path
                        _csv_files = get_csvs(repo, item.path)
                    elif item.path.endswith(".csv"):
                        print item.path
                        _csv_files[item.path] = item.decoded_content
                return _csv_files

            csv_files = get_csvs(repository, ".")

            for f in csv_files:
                csv_file = csv_files[f]
                new_deployment, created = Deployment.create_or_update_from_content(f, csv_file)
                print new_deployment.designator, created
                new_deployment.process_csv()
                print "processed"
                if created:
                    new_deployment.log_action(self.request.user, "Created.")
                else:
                    new_deployment.log_action(self.request.user, "Updated from Github.")
                new_deployment.log_action(self.request.user, 
                    "Processed CSV and created %d new data groups." % new_deployment.data_groups.count())
        return super(DeploymentGithubImportView, self).dispatch(request, *args, **kwargs)


class IngestionCreateView(generic.edit.CreateView):
    template_name = "deployments/ingestion_form.html"
    form_class = IngestionForm

    def form_valid(self, form):
        for field in INGESTOR_OPTIONS:
            if not getattr(form.instance, field):
                setattr(form.instance, field, INGESTOR_OPTIONS[field])
        form.instance.deployment = Deployment.get_by_designator(
            self.kwargs.pop('deployment_designator', None))
        return super(IngestionCreateView, self).form_valid(form)

class IngestionDetailView(generic.DetailView):
    model = Ingestion

    def get_object(self):
        try:
            object = Ingestion.objects.get(**{
                'deployment': Deployment.get_by_designator(self.kwargs.pop('deployment_designator', None)),
                'index': self.kwargs.pop('index', None),
                })
            return object
        except:
            raise Http404(u"No ingestion found.")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if "_ingest" in request.POST:
            self.object.log_action(request.user, "Ingesting deployment.")
            tasks.ingest.delay(self.object, annotations={'user': request.user, })
        return HttpResponseRedirect(self.object.get_absolute_url())

www/src/deployments/templates/deployments/deployment_base.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Deployments{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
{# <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a> #}
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block container %}
<div class="text-page">
  <div class="container">
	{% block content %}
	{% endblock %}
	</div>
</div>
{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}


www/src/deployments/templates/deployments/deployment_detail.html
{% extends "deployments/deployment_base.html" %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript">
	$(document).ready(function() {
		$(".link-row").click(function() {
			window.document.location = $(this).data("url");
		});
	});
</script>
{% endblock %}


{% block content %}
<div class="row">
	<div class="col-md-12">
		<h1>Deployment Details <small>[{{ object.designator }}]</small></h1>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Details</strong>
			</div>
			<div class="panel-body">
				<table class="table table.condensed">
					<tr>
						<th>Platform:</th>
						<td><a href="{% url 'deployments:list' %}?platform={{ object.platform }}">{{ object.platform }}</a></td>
					</tr>
					<tr>
						<th>Number:</th>
						<td>{{ object.number }}</td>
					</tr>
					<tr>
						<th>Data Source:</th>
						<td><a href="{% url 'deployments:list' %}?data_source={{ object.data_source }}">{{ object.data_source }}</a></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Tools & History</strong>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-9 short-viewport">
						<table class="table table-condensed table-monospace table-detailed">
							<thead>
								<tr>
									<th>Timestamp</th>
									<th>User</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								{% for action in object.actions.all|dictsortreversed:"timestamp" %}
								<tr class='main-row'>
									<td>{{ action.timestamp }}</td>
									<td>{{ action.user.get_full_name }}</td>
									<td>{{ action.action }}</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					<div class="col-md-3">
						<form enctype="multipart/form-data" action="" method="post">
							{% csrf_token %}
							<input type="submit" name="_process_csv" value="Reprocess CSV" class="btn btn-default"/>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Ingestions</strong>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-9 short-viewport">
						<table class="table table-condensed table-monospace table-detailed">
							<thead>
								<tr>
									<th>Index</th>
									<th>Timestamp</th>
									<th>Status</th>
									<th>Active</th>
								</tr>
							</thead>
							<tbody>
								{% for ingestion in object.ingestions.all|dictsortreversed:"timestamp" %}
								<tr class='main-row link-row' data-url="{% url 'deployments:ingestion_detail' object.designator ingestion.index %}">
									<td>{{ ingestion.index }}</td>
									<td>{{ ingestion.timestamp }}</td>
									<td>{{ ingestion.status }}</td>
									<td>{{ ingestion.active|yesno:"Active,Inactive" }}</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					<div class="col-md-3">
						<p>
							<a class="btn btn-default" href="{% url 'deployments:ingestion_create' object.designator %}">Add a new ingestion</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Data Groups</strong>
			</div>
			<div class="panel-body">
				<table class="table table-condensed table-hover table-monospace table-detailed">
					<thead>
						<tr>
							<th>File Mask</th>
							<th>Reference Designator</th>
							<th>uFrame Route</th>
							<th>Data Source</th>
						</tr>
					</thead>
					<tbody>
						{% for data_group in object.data_groups.all %}
							<tr class="main-row expand-row" data-target="#dataGroupDetail_{{ data_group.id }}" data-toggle="collapse" aria-expanded="false" aria-controls="dataGroupDetail_{{ data_group.id }}">
								<td>{{ data_group.file_mask }}</td>
								<td>{{ data_group.reference_designator }}</td>
								<td>{{ data_group.uframe_route }}</td>
								<td>{{ data_group.data_source }}</td>
							</tr>
							<tr class="collapse detail-row" id="dataGroupDetail_{{ data_group.id }}">
								<td colspan="4">Extra information</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
{% endblock %}

www/src/deployments/templates/deployments/deployment_form.html
{% extends "deployments/deployment_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<h1>Import a Deployment</h1>
		<p>Import a new deployment from a parameter CSV file.</p>
		<form enctype="multipart/form-data" action="" method="post">
			{% csrf_token %}
			{{ form|crispy }}
			<input type="submit" value="Save" class="btn btn-default"/>
		</form>
	</div>
</div>
{% endblock %}

www/src/deployments/templates/deployments/deployment_github_import.html
{% extends "deployments/deployment_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<h1>Import CSVs from Github</h1>
		<p>Import and update ingestion CSVs from Github repository.</p>
		<form enctype="multipart/form-data" action="" method="post">
			{% csrf_token %}
			<input type="submit" name="_import" value="Import from Github" class="btn btn-default"/>
		</form>
	</div>
</div>
{% endblock %}

www/src/deployments/templates/deployments/deployment_list.html
{% extends "deployments/deployment_base.html" %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript">
	$(document).ready(function() {
		$(".link-row").click(function() {
			window.document.location = $(this).data("url");
		});
	});
</script>
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h1>
			Deployments 
			{% if request.GET %}
				<small>
					[
					{% if request.GET.platform %}Platform: {{ request.GET.platform }} {% endif %}
					{% if request.GET.number %} {{ request.GET.number }} {% endif %}
					{% if request.GET.data_source %} {{ request.GET.data_source }} {% endif %}
					{% if request.GET.data_source_abbr %} {{ request.GET.data_source_abbr }} {% endif %}
					]
				</small>
			{% endif %}
		</h1>
		<table id="deployment-list" class="table table-condensed table-hover table-detailed">
			<thead>
				<tr>
					<th>Platform</th>
					<th>Number</th>
					<th>Data Source</th>
				</tr>
			</thead>
			<tbody>
				{% for deployment in object_list %}
					<tr class="main-row link-row" data-url="{% url 'deployments:detail' deployment.designator %}">
						<td>{{ deployment.platform }}</td>
						<td>{{ deployment.number }}</td>
						<td>{{ deployment.data_source }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

www/src/deployments/templates/deployments/ingestion_detail.html
{% extends "deployments/deployment_base.html" %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h1>Ingestion Details <small>[{{ object.designator }}]</small></h1>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
			</div>
			<div class="panel-body">
				<p><strong>Deployment</strong>: <a href="{% url 'deployments:detail' object.deployment.designator %}">{{  object.deployment }}</a></p>
				<p><strong>Ingestion Index:</strong> {{ object.index }}</p>
				<p><strong>Created On</strong>: {{ object.timestamp }}</p>
				<p>
					<ul>
						{% for action in object.actions.all %}
						<li>{{ action }}</li>
						{% endfor %}
					</ul>
				</p>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading"></div>
			<div class="panel-body">
				<form enctype="multipart/form-data" action="" method="post">
					{% csrf_token %}
					<input type="submit" name="_ingest" value="Ingest" class="btn btn-default"/>
				</form>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Data Files</strong>
			</div>
			<div class="panel-body">
				<table class="table table-condensed table-hover table-monospace table-detailed">
					<thead>
						<tr>
							<th>File Path</th>
							<th>Status</th>
						</tr>
					</thead>
					<tbody>
						{% for data_file in object.data_files.all %}
							<tr class="main-row expand-row" data-target="#dataFileDetail_{{ data_file.id }}" data-toggle="collapse" aria-expanded="false" aria-controls="dataFileDetail_{{ data_file.id }}">
								<td>{{ data_file.file_path }}</td>
								<td>{{ data_file.status }}</td>
							</tr>
							<tr class="collapse detail-row" id="dataFileDetail_{{ data_file.id }}">
								<td colspan="2">
								{% for event in data_file.events.all %}
									{{ event.timestamp}}: {{ event.type }}: {{ event.route }}<br>
								{% endfor %}
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<div class="row">
	{% for fieldset in object.configuration_fieldsets %}
	<div class="col-md-3">
		<fieldset>
			<legend>{{ fieldset.heading }}</legend>
			{% for field in fieldset.fields %}
				<p>
					<strong>{{ field.label }}</strong><br>
					{{ field.value }}
				</p>
			{% endfor %}
		</fieldset>
	</div>
	{% endfor %}
</div>
{% endblock %}

www/src/deployments/templates/deployments/ingestion_form.html
{% extends "deployments/deployment_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h1>Create a new Ingestion</h1>
			{% crispy form %}
		</form>
	</div>
</div>
{% endblock %}