www/src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    # url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

www/src/deployments/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

urlpatterns = [

    # Deployments
    url(r'^$', 
        login_required(views.DeploymentListView.as_view()), name="list"),
    url(r'^create/$', 
        login_required(views.DeploymentCreateView.as_view()), name="create"),
    url(r'^github_import/$', 
        login_required(views.DeploymentGithubImportView.as_view()), name="github_import"),
    url(r'^detail/(?P<slug>[-\w]+)/$', 
        login_required(views.DeploymentDetailView.as_view()), name='detail'),

    # Ingestions
    url(r'^detail/(?P<deployment_designator>[-\w]+)/new-ingestion$', 
        login_required(views.IngestionCreateView.as_view()), name='ingestion_create'),
    url(r'^detail/(?P<deployment_designator>[-\w]+)/ingestions/(?P<index>[-\w]+)$', 
        login_required(views.IngestionDetailView.as_view()), name='ingestion_detail'),
    ]

www/src/diman/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import deployments.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^deployments/', include(deployments.urls, namespace='deployments')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

www/src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

www/src/templates/_brandname.html
OOI Data Ingestion Management

www/src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>

www/src/templates/base.html
<!DOCTYPE html>
<html lang="en">
		{% load staticfiles %}
		{% load thumbnail %}
		
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="{% block description %}{% endblock description %}">
		<meta name="author" content="Arun Ravindran">
		<link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

		<title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

		<!-- Bootstrap core CSS -->
		<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

		<!-- Custom styles for this site -->
		{% block styles %}
		<link href="{% static 'site/css/main.css' %}" rel="stylesheet">
		{% endblock styles %}

		<!-- Custom tags for the head tag -->
		{% block extrahead %}{% endblock extrahead %}

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>

		{% block navbar %}
		<div class="navbar navbar-default navbar-fixed-top" role="navigation">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'home' %}">
						{% block navbar-brand %}
							<img src="{% static 'site/img/logo.png' %}" alt="logo">
							{% include "_brandname.html" %}
						{% endblock %}
					</a>
				</div>
				{% block navbar-menu %}
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						{% block navbar-left %}{% endblock %}
					</ul>
					<ul class="nav navbar-nav navbar-right">
						{% block navbar-right %}
							{% if user.is_authenticated %}
								{% if user.is_staff %}
								<li><a href="{% url 'admin:index' %}">Admin</a></li>
								{% endif %}
								<li class="dropdown">
									<a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
										<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
										{{ user.get_full_name|truncatechars:20 }}
										<span class="caret"></span>
									</a>
									<ul class="dropdown-menu" role="menu">
										<li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
										<li><a href="{% url 'accounts:logout' %}">Logout</a></li>
									</ul>
								</li>
							{% endif %}
						{% endblock %}
					</ul>
					</ul>
				</div><!--/.nav-collapse -->
				{% endblock %}
		</div>
		{% endblock navbar %}

		{% block messages %}
			{% if messages %}
				{% for message in messages %}
					<div class="alert alert-{{ message.tags }}">	<!-- singular -->
						<a class="close" data-dismiss="alert">×</a>
						{{ message|safe }}
					</div>
				{% endfor %}
			{% endif %}
		{% endblock %}

		{% block splash %}
		{% endblock splash %}
		
		{% block container %}
		<div class="container">

			<div class="starter-template">
				<h1>New Project</h1>
				<p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
			</div>

		</div><!-- /.container -->
		{% endblock container %}

		<!-- Site footer -->
		{% block footer %}
			<!-- Some social button for contact will do -->
			<a name="contact"></a>
			<div class="container">
						<div class="footer">
				<div class="row">
					<div class="col-lg-12 text-center">
							<p>&copy; {% now 'Y' %} Rutgers, The State University of New Jersey</p>
					</div>
				</div>
						</div>
			</div>
		{% endblock %}

		<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
		<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
		{% block scripts %}
		{% endblock scripts %}
	</body>
</html>

www/src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
{# <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a> #}
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block container %}
<!-- Benefits of the Django application -->
<div class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<strong>Ingestion</strong><br>
						<small>Manage ingestions of cabled and uncabled data.</small>
					</div>
					<div class="panel-body">
						<ul>
							<li><a href="{% url 'deployments:create' %}">Create a Deployment</a></li>
							<li><a href="{% url 'deployments:list' %}">View Deployements</a></li>
						</ul>
					</div>
				</div>
	    </div>
			<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<strong>Triage</strong><br>
						<small>Verify data ingested into the system.</small>
					</div>
					<div class="panel-body">
						<ul>
							<li>View Logs</li>
						</ul>
					</div>
				</div>
			</div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}